<?php
$page ='terms';
?>

<?php include 'inc/head.php'; ?>

<title>Ivas</title>
<meta name="description" content="" />
<link rel="canonical" href="" />
<meta name="robots" content="noindex, nofollow">
<?php include 'inc/header.php'; ?>

 
		  
<section class="contact-us inquiry-model my-5">
    <div class="container">
			<div class="terms-condition">
			<h2>Terms &amp; Conditions</h2>
			<h6>GENERAL</h6>
			<p>The terms and conditions set out in this Terms of Use, including Customer Dos and Don’ts, IVAS Quality Promise, Cancellation Policy, Return, Exchange & Refund Policy, Payment Policy and Privacy Policy (collectively, the “Terms”) govern the access to and use of this website _____________ (“Site”) and any associated software or mobile (collectively, the “Platform”) and services provided by affiliates, parent company, subsidiary, franchisee (“IVAS”, “we”, “us”, “our”) via the Platform (collectively “Services”).  </p>
			<p>The Terms govern all users of the Platform and/or Services (collectively “Users” and each a “User”, “you”, “your” and “yours”) and constitute legally binding contract between each User and IVAS. Please read these Terms carefully before registering with IVAS or accessing any materials, information, purchasing products or availing services on the Platform. If you are not agreeable to any terms or Privacy Policy, you should not proceed to use this Platform and underlined services. You signify your acceptance to the Terms by clicking on the “I Accept” button provided on the Platform. By registering on the Platform, you confirm that you are legally competent to contract and transact on the Platform.</p>
			<p>The access to or use of certain areas or features of the Platform and/or Services may be subject to separate policies, standards or guidelines, or may require Users to accept additional terms and conditions as published on the Platform or via a separate written agreement.</p>
			<p>IVAS reserves the right, in its sole discretion, to vary any parts of the Terms any time. Users should periodically visit the relevant page containing the terms and conditions of the Platform or Services to review the current prevailing terms and conditions so that they are aware of any revision by which they are bound. In the event of any changes to the Terms, we will either notify Users via e-mail to their email address registered with IVAS or post the changes on the relevant page of the Platform and update the “Last Updated” date at the top of that page as the effective date of change. However, any changes will not apply retrospectively. Users’ continued use of Platform and/or Services after any such changes constitutes acceptance of the latest Terms.</p>
			
			<h6>DEFINITIONS AND INTERPRETATION</h6>
			<p>The following words and expressions have the following meanings unless inconsistent with the context or stated otherwise:</p>
			<p>“Content” means any data, text, software, music, sound, photographs, graphics, video, messages or other materials, including but without limitation to, company logos, trademarks, copyrighted materials and Third Party Resources, displayed, published or made available on through the Platform.</p>
			<p>“Intellectual Property Rights” means all intellectual property rights (whether registered or not) including, but not limited to, copyright (including copyright in computer software), patents, logos, trademarks or business names, design rights, database rights, know-how, trade secrets and rights of confidence in connection with the Platform, Services and/or Content.</p>
			<p>“IVAS Technology” means IVAS’s proprietary technology underlying the Platform and/or Services, including internet operations design, content, software tools, hardware designs, algorithms, software (in source and object forms), source codes, user interface designs, architecture, class libraries, objects and documentation (both printed and electronic), know-how, trade secrets and any related intellectual property rights throughout the world (whether owned by IVAS or its licensors) in connection with the Platform and/or Services, and also including any derivatives, improvements, enhancements or extensions of the technology conceived, reduced to practice, or developed by IVAS from time to time that are not uniquely applicable to Users or that have general applicability in the art.</p>
			<p>“Ivaspreneuer(s)” shall mean and include freelance designers, design studios, contracting firms, or design & build studios which are associated with IVAS as third party independent service providers.</p>
			<p>“Parties” means collectively IVAS and a User, and a “Party” means any of them.</p>
			<p>“Third Party Vendor(s) and Service Provider(s)” means independent vendor(s) and/or service provider(s) offering, providing or supplying products or services via the Platform who are independent third party operators, including Ivaspreneurs. </p>
			<p>“User(s)” refer to person or individuals who visits, uses, browses, or otherwise becomes a buyer on the Platform and avails any service through the Platform and/or deals with or transacts with the Platform in any manner , which may include Third Party Vendors and Service Providers and are the end-customers of products or services provided by Third Party Vendors and Service Providers, as the case may be.</p>
			<p>“User’s Content” means any data, text, software, music, sound, photographs, graphics, video, messages or other materials, including but without limitation to, company logos, trademarks and copyrighted materials displayed, published or made available on or through the Platform by any User.</p>
			<p>References to Clauses are to the clauses herein.</p>
			<p>The headings are for convenience only and shall not affect the interpretation of the Terms.
Unless the context otherwise requires or permits, references to the singular number shall include references to the plural number and vice versa; and words denoting any gender shall include all genders.
</p>
			<p>The expression “person” means any individual, corporation, partnership, association, limited liability company, trust, governmental or quasi-governmental authority or body or other entity or organisation.</p>
			<h6>ELIGIBILITY TO USE</h6>
			<p>Users must be at least 18 years old and able to enter into legally binding contracts to access and use the Services and/or register an account with IVAS to use the Services. By accessing or using the Platform and/or Services, Users represent and warrant that they are 18 or older and have the legal capacity and authority to enter into a contract. If you represent any other person, natural or artificial, you confirm that you have the requisite authority and power to bind such person to these Terms.</p>
			<p>For transparency and fraud prevention purposes, and to the extent permitted by law, we reserve the right, but have no obligation, to (i) ask Users to provide a form of government identification or other information or undertake additional checks designed to help verify the identity or background of Users, and (ii) screen Users against third party databases or other sources.</p>
			<h6>ACCOUNT REGISTRATION</h6>
			<p>In order to avail services from IVAS Platform, and/or purchase products from Third Party Vendors and Service Providers, you will have to register on the Platform and create an account (“Account”) by providing details about yourself, including name, address, contact details and such other details as may be required. You shall ensure and confirm that the information provided by you is complete, accurate and up-to-date. If there are any changes you shall promptly update such information on the Platform via your Account. You will be responsible for maintaining the confidentiality of your Account and its information, and are fully responsible for all activities that occur therein. IVAS will not be liable for any loss or damage arising from your failure to comply with this provision and you may be held liable for any losses incurred by IVAS and/or its Third Party Vendors and Service Providers as a consequence. In any event, we reserve the right, in our sole discretion, to approve or refuse registration of an Account by any person.</p>
			<p>You hereby authorise IVAS to collect, store, retain, process and use personal data, including your contact information provided to the Company in accordance with our Privacy Policy. You hereby permit the Company to contact you through phone/SMS/whatsapp/e-mail, provided all such communication shall be undertaken solely in relation to the Service and your personal data, including contact information shall be kept confidential in accordance with the Privacy Policy.</p>
			<p>Users are responsible for designating any other individuals who have the right or authority to access, use or administer their Accounts for and on their behalf (“Authorised Users”). Whilst Users may permit such Authorised Users to access and use their Accounts (e.g. to perform transactions under their Accounts, update Users’ details, etc), Users registered with IVAS shall remain fully liable under the Terms for all acts and omissions of their Authorised Users, whether or not such Authorised Users have acted in accordance with Users’ instructions. Users are solely responsible for maintaining the confidentiality of their password and other information relating to their Accounts, and any and all activities that occur under their Accounts. Users agree to (i) immediately notify IVAS of any unauthorised use of their Accounts, password, or any other breach of security, and (ii) ensure that Users or Authorised Users exit from their Accounts at the end of each session. IVAS will not be liable for any loss or damage arising from Users’ failure to comply with this provision.</p>
			<p>You acknowledge that we may establish general practices and limits concerning use of the Platform, including without limitation to the maximum period of time that data or other content will be retained by the Platform and the maximum storage space that will be allotted on our servers on your behalf. You agree that we have no responsibility or liability for the deletion or failure to store any data or other content maintained or transmitted by the Platform. You acknowledge that we reserve the right to terminate any Account that is inactive for an extended period of time. You further acknowledge that we reserve the right to change these general practices and limits at any time, at our sole discretion, with or without notice.</p>
			<p>You may not assign or otherwise transfer your Account to any person without the prior written authorisation by IVAS.</p>
			<p>By registering for an Account, you hereby expressly agree to receive communications by way of SMS and/or e-mails from IVAS and other third parties relating to the products and/or services provided through the Platform. You can unsubscribe or opt-out from receiving communications through SMS and e-mail anytime by using the opt-out option provided in such communications or sending us an e-mail to opt-out at grievanceofficer@IVAS.com/legal@IVAS.com.</p>
<h6>OUR SERVICE</h6>
<p>We provide one stop Platform for home interior design services and shall provide services in relation to the execution of the finalised design on a turn-key basis and in relation to purchase of products and services from Third Party Service Providers. The Customer shall pay the Company immediately upon any payments becoming due in accordance with the Payment Terms. The Company shall provide and shall ensure that all Third Party Vendors or Service Providers (if any) also provide warranty/defect liability period on the civil work and woodwork related items. To the extent where the products or services are provided by Third Party Vendors and Service Providers, IVAS is not responsible for setting or controlling the prices displayed on the Platform or offered by such Third Party Vendors and Service Providers. </p>
<p>Third Party Vendors and Service Providers are responsible for their products or services offered or supplied to Users, and IVAS shall not be responsible for and does not provide any warranty or guarantee whatsoever with respect to (i) the quality, safety, suitability, or legality of any product or service of Third Party Vendors and Service Providers, (ii) the truth or accuracy of any product or service descriptions of Third Party Vendors and Service Providers, or (iii) the performance or conduct of Third Party Vendors and Service Providers. IVAS shall only be responsible to ensure that Users and Third Party Vendors and Service Providers deal with each other in accordance with and within the parameters of the Terms.</p>
<p>By accepting these terms and conditions you acknowledge and agree that IVAS shall not and is not required to mediate or resolve any dispute or disagreement between Users and Third Party Vendors and Service Providers. All products and services on the Platform may be subject to additional terms and conditions imposed by the Third Party Vendors and Service Providers, which Users are obligated to have read and accepted at the time of placing the order or before engaging the relevant Third Party Vendors and Service Providers.
</p>
<p>IVAS reserves the right to amend/revise the product/service offerings of styles and construction options within the IVAS product/service line and professional services, from time to time, as its sole discretion.</p>
<p>The Terms of use shall be subject to our payment, cancellation, refund & returns and warranty policies. Please read them carefully before availing any services on the Platform.</p>
<h6>General Obligations and Restrictions</h6>
<p>You shall solely be responsible for maintaining the necessary computer equipment, internet connections and telecommunication charges that may be required to access, use and transact on the Platform.</p>
<p>Subject to full compliance with the Terms, IVAS grants you a non-exclusive, limited privilege to access and use the Platform or Services (including purchasing products and availing services). You agree to use the Platform for legitimate purposes, in accordance with the Terms and any applicable law, regulation or generally accepted practices or guidelines regarding the use of the Platform and/or Services, including your online conduct.
</p>
<p>In using the Platform and/or Services, you agree to not engage in activities that may adversely affect the use of the Platform by the IVAS and/or other Users. Further, you agree not to host, display, upload, modify, publish, send, share or update any information (i) which does not belong to you or you do not have the right to host, display, upload, modify, publish, send, share or update, (ii) that is offensive, obscene, disparaging, defamatory, abusive, harassing, threatening, harms minors in any way, infringes the intellectual property rights or otherwise in violation of any law, the legal rights of others or is otherwise unlawful or objectionable in any manner, (iii) deceives or misleads the addressee regarding origin of such message, (iv) impersonates anyone, (v) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource, or (vi) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation. You shall not reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from the Platform.
To the extent where the Platform allows you to post, upload, transmit or make available any User’s Content, you shall be responsible for such User’s Content and agree that (i) you will ensure that such User’s Content is not offensive and is in accordance with applicable laws, (ii) although all intellectual property rights subsisting in any User Content will be owned by you or your licensors, you hereby grant IVAS and its subsidiaries and affiliates a non-exclusive, perpetual, royalty-free, worldwide, transferrable and sub-licensable right to use, reproduce both electronically and otherwise, display, distribute, modify, adapt, publish, translate, and create derivative works from any and all such User Content (excluding personally identifiable information) including for the purposes of advertising and marketing the Platform or Services, and (iii) we are under no obligation to store, retain, publish or make available any User Content uploaded by you and that you shall be responsible for creating backups of any such User’s Content if necessary.
</p>
<p>You shall not directly or indirectly, in any capacity, solicit, engage, approach or encourage the solicitation or approach of a Third Party Vendor or Service Provider, including Ivasprenuers to provide direct services to You or avail same or similar services provided on IVAS Platform, independently without booking through your Account on IVAS Platform. Any transactions and/or payment between You and Third Party Service Providers without booking through IVAS Platform shall be deemed as “Unauthorised Transactions” and IVAS shall have no liability for such Unauthorised Transactions. You agree and acknowledge that this is a reasonable restriction for the protection of your property and the Third Party privacy of Service Providers. You further agree that you will be solely responsible for any potential harm, damage or loss from the violation of this clause without any claim on IVAS.
</p>
<p>We cannot guarantee the identity of any other Users with whom you may interact with in the course of using the Platform. We also cannot guarantee the authenticity and accuracy of any User’s Consent which other Users or Third Party Vendors and Service Providers may provide. All User’s Content accessed by you using the Platform is at your own risk and you will be solely responsible for any damage or loss to any party resulting therefrom.
</p>
<h6>UPDATES, MODIFICATIONS AND AVAILABILITY</h6>
<p>IVAS may modify or upgrade the features and functionality of the Platform and/or Services from time to time, and reserve the right to make upgrades, updates, modifications and changes as it deems fit. Users understand that such upgrades or changes may result in interruption, modification, failure, delay or discontinuation of the Platform and/or Services or any function or feature thereof. In this regard, Users acknowledge and agree that IVAS assumes no liability, responsibility or obligation for any such interruption, modification, failure, delay or discontinuation associated with the Platform and/or Services.</p>
<p>Notwithstanding anything contained in the Terms, IVAS reserves the right to modify or discontinue, temporarily or permanently, the Platform and/or Services (or any part thereof). You agree that IVAS shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Platform and/or Services.
</p>
<h6>INTELLECTUAL PROPERTY RIGHTS</h6>
<p>The Platform, text, graphics, user interfaces, visual interfaces, sounds, artwork, designs, and computer code on the Platform is owned and controlled by IVAS and the design, structure, selection, coordination, expression, look and feel and arrangement on the Platform is protected by copyright, patent and trademark laws, and various other intellectual property rights.
</p>
<p>The Platform, Content and IVAS Technology underlying the Platform and Services are the property of IVAS and/or its licensors, and are protected by copyright and/or other intellectual property rights. Except as expressly authorised by IVAS, Users agree to not modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Platform and/or Content, in whole or in part. The word “IVAS” and associated logos are the trademarks, trade names and/or service marks of IVAS, and Users agree not to display or use in any manner such names and/or marks without IVAS’s prior written authorisation. In using the Platform, Users shall not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods. Users further acknowledge that they have no right to have access to any aspect of the Platform in source-code form, and agree not to copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in IVAS Technology. Any uses of the Platform and/or Content not expressly permitted herein are prohibited, and any rights thereof not expressly granted herein are reserved by IVAS.
</p>
<p>By using the Platform and/or Services, Users will not acquire any right, title or interest in or to the Intellectual Property Rights except for the limited right to use the Platform and/or Services granted to Users pursuant to the Terms. All goodwill generated from the use of the Platform, Content and/or Services will inure to IVAS’s exclusive benefit.
</p>
<p>To the extent where Users provide IVAS with any suggestions, comments, improvements, ideas or other feedback (“Feedback”), Users hereby assign ownership of all intellectual property rights subsisting in that Feedback to IVAS and acknowledge that IVAS can use and share such Feedback for any purpose in its sole discretion.
</p>
<p>Other company, product, and service names and logos used and displayed via the Platform may be trademarks or service marks of their respective owners who may or may not be endorsed by, or affiliated with, or connected to IVAS.</p>
<h6>THIRD PARTY RESOURCES</h6>
<p>The Platform may contain links to third party’s websites, products, services, information, advertisement or other materials (“Third Party Resources”) that are not owned or controlled by IVAS, or the Services may be accessible through Third Party Resources. Links to Third Party Resources do not constitute an endorsement or recommendation by IVAS of such Third Party Resources. When Users access Third Party Resources, Users do so at their own risk. Users hereby represent and warrant that they have read and agree to be bound by all applicable policies of any Third Party Resources relating to the use of their services and act in accordance with those policies, in addition to Users’ obligations under the Terms. Users also acknowledge and agree that IVAS has no control over, and assumes no responsibility or liability for, the content, accuracy, privacy policies, or practices of or opinions expressed in any Third Party Resources. In addition, IVAS will not and cannot monitor, verify, censor or edit the content of any Third Party Resources. Users expressly relieve and hold harmless IVAS from any and all liability arising from the use of any Third Party Resources.
</p>
<h6>PRIVACY POLICY</h6>
<p>We view protection of your privacy as a very important principle. We understand clearly that you and your Personal Information is one of our most important assets. We store and process your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act, 2000 and Rules there under. Our current Privacy Policy is available at ______________
</p>
<h6>DISCLAIMER OF LIABILITIES</h6>
<p>You expressly understand and agree that, to the maximum extent permitted by applicable law and unless otherwise expressly specified, the Platform, products (including but not limited to software) and Services are provided by IVAS on an “as is” and “as available” basis without warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose, unless specifically provided otherwise. Your interactions and transactions with organisations and/or individuals (including Third Party Vendors and Service Providers) found on or through the Platform, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organisations and/or individuals. You should conduct whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. In the event that you have a dispute with one or more other users or third parties, you hereby release IVAS, its holding company, subsidiaries, officers, directors, employees, agents and successors from claims, demands, and damages (actual and consequential) of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such dispute.
</p>
<p>Without limiting the foregoing, IVAS makes no representation or warranty (i) that the Platform or Services will meet your requirements; (ii) that your use of the Platform or Services will be uninterrupted, timely, secure or error-free, (iii) that the results that may be obtained from the use of the Platform or Services will be effective, accurate or reliable, (iv) that the quality of the Platform and/or Services will meet your expectations, (v) that any errors or defects in the Platform will be corrected, or (vi) that the credentials or description of any products or services offered by Third Party Vendors and Service Providers are accurate, complete or reliable. No advice or information, whether oral or written, obtained by you from IVAS or through use of the Platform shall create any warranty not expressly stated in the terms of use.
</p>
<p>IVAS will not be liable for any loss that you may incur as a consequence of unauthorized use of your Account or account information in connection with the Platform and/or products and services from IVAS and/or Third Party Vendors and Service Providers, either with or without your knowledge.
</p>
<p>While IVAS has endeavored to ensure that all the information on the Platform is correct, IVAS neither warrants nor makes any representations regarding the quality, accuracy or completeness of any data, information or service. IVAS shall not be responsible for the delay or inability to use the Platform or related functionalities, the provision of or failure to provide functionalities, or for any information, software, functionalities and related graphics obtained through the Platform, or otherwise arising out of the use of the Platform, whether based on contract, tort, negligence, strict liability or otherwise.
</p>
<p>IVAS shall not be held responsible for non-availability of the Platform during periodic maintenance operations or any unplanned suspension of access to the Platform that may occur due to technical reasons or for any reason beyond our control. You understand and agree that any material or data downloaded or otherwise obtained through the Platform is done entirely at your own discretion and risk, and that you will be solely responsible for any damage to your computer systems or loss of data that results from the download of such material or data.
</p>
<p>You may see advertising material submitted by third parties on the Platform. Each individual advertiser is solely responsible for the content of its advertising material and we accept no responsibility for the content of such advertising material, including, without limitation, any error, omission or inaccuracy therein.
</p>
<h6>INDEMNIFICATION AND LIMITATION OF LIABILITY</h6>
<p>You agree to indemnify, defend and hold harmless IVAS and Third Party Vendors and Service Providers for any third party claims due to, or arising out of, or in connection with, your use of the Platform or Services, any misrepresentation with respect to the data or information provided by you, your violation of the Terms, violation of any rights of another, including any intellectual property rights.
</p>
<p>In no event shall IVAS, its officers, directors, consultants, agents and employees, be liable to you or any third party for any direct, special, incidental, indirect, ancillary, exemplary, consequential or punitive damages whatsoever, arising out of or in connection with your use of or access to the Platform, Services and/or products and service purchased on or through the Platform. This includes, but is not limited to injury, claim, loss of data, loss of income, loss of profit or loss of opportunity, loss of or damage to property, damages for monetary loss, goodwill, use, data or other intangible loss, resulting from or arising out of the use of or the inability to use the Platform or Services thereof, even if we have been advised or become aware of the possibility of such damages or loss or that such loss was foreseeable. Further, IVAS shall not be liable for any products, services, acts or omissions of Third Party Vendors and Service Providers. However, nothing in the Terms shall limit or exclude (i) any other liability that cannot be excluded by law, or (ii) your statutory rights.
</p>
<p>IVAS is not responsible for incomplete, illegible, misdirected or stolen entries. To the fullest extent permitted by the laws of the jurisdiction in which we operate, we also exclude legal responsibility for any loss to you arising from use of our Platform or Service including from viruses, bugs or other technical malfunction, the failure of any software or equipment that impedes the operation of our Platform or the placing of entry fees, or for delays and disruptions on our Platform, a suspension or other action taken with respect to your account, and for any loss of actual or anticipated income, loss of revenue, loss of goodwill and reputation, loss of anticipated savings, loss of use, loss of data, increased costs and expenses, wasted expenditure and any indirect, special and consequential damages, arising as a result of your use of the Platform or Services thereof, whether or not such loss or damage is foreseeable, foreseen or known.
</p>
<p>We make reasonable efforts to ensure that the products, data, statistics, and other content and material appearing on or forming part of our Platform and Service is complete, accurate, and up-to-date. We do not, however, make any representations, warranties or guarantees (whether express or implied) in this respect.
</p>
<h6>TERM, VIOLATION, SUSPENSION AND TERMINATION</h6>
<p>The agreement between IVAS and each User under the Terms shall take effect upon the earlier of (i) the User’s commencement of the use of the Platform and/or Services, or (ii) registration of an Account, or (iii) execution of a written agreement with IVAS in respect of the use of the Services, and will remain in full force and effect for as long as relevant User continue to use the Platform and/or Services. The terms will continue to apply until terminated by either you or IVAS. If you object to the Terms or are dissatisfied with the Platform or Services, your only recourse is to close your Account on the Platform and/or stop accessing or using the Platform or Services.
</p>
<p>IVAS may suspend or terminate your Account with or without notice at any time without incurring any liability whatsoever to you or any third party if IVAS believes, in its sole and absolute discretion, that you have infringed, breached, violated, abused, or unethically manipulated or exploited any term or condition of these Terms or anyway otherwise acted unethically. Notwithstanding anything in this clause, these terms will survive indefinitely unless and until IVAS chooses to terminate them. In this instance, IVAS reserves the right to remove and discard data in and content of your Account but may preserve your transaction details for purposes of tax, legal or regulatory compliance. Any suspected fraudulent, abusive or illegal activity that may be grounds for such suspension, discontinuance or termination may be referred to the appropriate law enforcement authorities. Upon termination or account closure your transactions details may be preserved by IVAS for purposes of tax or regulatory compliance.
You agree that any violation by you of the Terms may cause irreparable harm to IVAS for which monetary damages would be inadequate, and you consent to IVAS obtaining any injunctive or equitable relief that it deems necessary or appropriate in such circumstances. These remedies are in addition to any other remedies that IVAS may have at law or in equity. If IVAS takes any legal action against you, they will be entitled to recover from you, and you agree to pay, all reasonable attorneys’ fees and costs of such action, in addition to any other relief that may be granted.
</p>
<p>Upon termination of the agreement with a User pursuant to the Terms, the User’s access and use rights to the Platform and/or Services and other rights hereunder shall terminate. Save for any obligations which are expressed to survive, each Party’s further rights and obligations shall cease immediately, provided that such termination shall not affect a Party’s accrued rights and obligations as at the date of such termination.
</p>
<p>Notwithstanding the suspension or termination of your Account, you shall remain liable to fulfil all transactions and pay for such transactions that you have already committed to prior to suspension of termination of your Account subject to the applicable terms and conditions governing such transactions (e.g. the terms and conditions agreed between you and Third Party Vendors and Service Providers).
</p>
<p>At all times IVAS reserves the right to discontinue Services if You are found to be in violation of its Anti-Bribery, Anti-Discrimination or Sexual Harassment Policies.</p>
<h6>RELATIONSHIP BETWEEN PARTIES</h6>
<p>Nothing in the Terms shall deem to constitute a partnership between us and you and it is hereby understood and parties shall be related on principal to principal basis only, and is not a legal representative, partner, or agent of the other Party. Neither Party shall have any right, power or authority, whether express or implied, to create any obligation on behalf of the other Party.
</p>
<h6>ANTI-BRIBERY POLICY</h6>
<p>Users shall not commit any act of bribery or corruption, including directly or indirectly give, make, offer or receive or agree to make any payments, contributions, gifts, entertainment or other advantages for the purpose of obtaining or retaining business which a reasonable person would consider to be unethical, illegal or improper, or which is in violation of any anti-bribery or anti-corruption laws and regulations. A violation of this provision will result in immediate termination of your Account and access to or use of the Platform and/or Services.
</p>
<h6>ANTI-DISCRIMINATION POLICY</h6>
<p>IVAS is committed in providing a community environment between Users that is free from harassment. Harassment based upon an individual's sex, race, ethnicity, national origin, age, religion or any other legally protected characteristics will not be tolerated. All Users, including end-users and Third Party Vendors and Service Providers, and our employees or agents, are expected and required to abide by this policy. A violation of this provision will result in immediate termination of your Account and access to or use of the Platform and/or Services.</p>
<h6>SEXUAL HARASSMENT</h6>
<p>Sexual harassment is behavior of a sexual nature that is unwelcome and offensive to the person or persons it is targeted toward. Examples of harassing behavior may include unwanted physical contact, foul language of an offensive sexual nature, sexual propositions, sexual jokes or remarks, obscene gestures, and displays of pornographic or sexually explicit pictures, drawings, or caricatures. All Users, including end-users and Third Party Vendors and Service Providers, and our employees or agents, are expected and required to abide by this policy. A violation of this provision will result in immediate termination of Your Account and access to or use of the Platform and/or Services.
</p>
<h6>REPORT ABUSE</h6>
<p>In the event you come across any abuse or violation of the Terms or if you become aware of any objectionable content on the Platform, please report the same to the following e-mail address: _______________ 
</p>

<h6>REPORT IP INFRINGEMENT</h6>
<p>If you believe the Platform or any products/services offered on or through the Platform violates your intellectual property, you must please promptly notify IVAS in writing at __________. Such notifications should only be submitted by the owner of the intellectual property or an agent authorized to act on his/her behalf. However, any false claim by You may result in the termination of your access to or use of the Platform or Services. You are required to provide the following details in the notice: 
</p>
<p>Your contact details, such as your address, telephone number, and/or email; <br>
The intellectual property that you believe is being infringed; <br>
The item that you think is infringing and include sufficient information about where the material is located on the Platform; <br>
A statement that you believe in good faith that the item you have identified as infringing is not authorized by the intellectual property owner, its agent, or the law to be used in connection with the Platform; Your contact details, such as your address, telephone number, and/or email; A statement that the information you provided in your notice is accurate, and that you are the intellectual property owner or an agent authorized to act on behalf of the intellectual property owner whose intellectual property is being infringed; and </br>
Your physical or electronic signature </p>

<h6>NOTICE</h6>
<p>All notices from IVAS will be served by email to your registered email address or by general notification on the Platform.
</p>
<p>Any notice provided to IVAS pursuant to the Terms should be sent to ___________ with subject line - Attention: TERMS OF USE.
</p>

<h6>OTHER PROVISIONS</h6>
<p>The Terms constitute the entire agreement between the Parties concerning the subject matter herein and supersedes all previous terms and conditions, understanding, representations and warranties relating to that subject matter.</p>
<p>You cannot assign or otherwise transfer any of your rights and obligations under the Terms to any third party. IVAS’s rights and obligations under the Terms are freely transferable by IVAS to any third party without the requirement of seeking your consent.
</p>
<p>Your affirmative act of using and accessing the Platform constitutes your electronic signature to the Terms, making the terms of this document binding upon you.
</p>
<p>If, for any reason, a court of competent jurisdiction finds any provision of the Terms, or any portion thereof, to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to give effect to the intent of the Parties as reflected by that provision, and the remainder of the terms shall continue in full force and effect.
</p>
<p>Any failure or delay by IVAS to enforce or exercise any provision of the Terms, or any related right, shall not constitute a waiver by IVAS of single or partial exercise of that provision or right, power or privilege hereunder at law or equity.
</p>
<p>Save as otherwise specifically provided in the Terms, the Parties hereunder shall not be liable for failures or delays in performing their obligations hereunder arising from any Event of Force Majeure (defined below), and in the event of any such delay, the time for all Parties’ performance shall be extended for a period equal to the time lost by reason of the delay which shall be remedied with all due dispatch in the circumstances. “Event of Force Majeure” means any cause beyond the reasonable control of a Party, including any act of God, outbreak, or epidemic of any kind, communicable and virulent disease, strike, flood, fire, embargo, boycott, act of terrorism, insurrection, war, explosion, civil disturbance, shortage of gas, fuel or electricity, interruption of transportation, governmental order, unavoidable accident, or shortage of labour or raw materials.
</p>
<h6>GOVERNING LAW AND DISPUTE RESOLUTION</h6>
<p>Irrespective of the country from which Users access or use the Platform and/or Services, to the extent permitted by law, the Terms shall be governed in accordance with the laws of India without regard to choice or conflicts of law principles, and Users hereby agree to submit to the exclusive jurisdiction of the civil courts of Thane, Maharashtra to resolve any claims or disputes which may arise in connection with the Terms.
</p>
<h6>GRIEVANCE OFFICER</h6>
<p>In accordance with Information Technology Act 2000 and rules made there under and the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer are provided below:
</p>
<p>Name: </br>
Designation: </br>
E-mail: </br>
Time: </br>
</p>
<h6>UPDATE</h6>
<p>This document was last updated on ____________ Any update, amendment, or changes to our Terms of Use will be posted on this page.
</p>
</div>
</div>
</section>

<?php include 'inc/footer-js.php'; ?>
<?php include 'inc/footer.php'; ?>